# Generated by Django 5.0.4 on 2025-05-31 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.IntegerField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='La cédula debe tener 7 u 8 dígitos sin guiones ni puntos.', regex='^\\d{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El teléfono debe tener 9 dígitos.', regex='^\\d{9}$')]),
        ),
    ]
