# Generated by Django 5.0.4 on 2025-05-31 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_user_ci_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
