# Generated by Django 5.0.4 on 2025-05-31 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='La cédula debe tener 7 u 8 dígitos, sin guiones, ni puntos.', regex='^[0-9]{7,8}$')], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El teléfono debe tener 10 dígitos.', regex='^[0-9]{10}$')]),
        ),
    ]
