# Generated by Django 5.0.4 on 2025-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_user_ci_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de asignación'), ('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('MONITOREO', 'Jefe de Monitoreo'), ('ANALISIS', 'Jefe de Análisis'), ('EXPEDIENTES', 'Jefe de Expedientes'), ('RELEVAMIENTO', 'Jefe de Relevamiento'), ('SIG', 'Jefe de SIG')], default='PENDIENTE', max_length=20, verbose_name='Rol'),
        ),
    ]
